6_25.exe:6_25.o account.o date.o
		g++ 6_25.o account.o date.o -o 6_25.exe

6_25.o:6_25.cpp account.h date.h
		g++ -c 6_25.cpp -o 6_25.o

account.o:account.cpp account.h
		g++ -c account.cpp -o account.o

date.o:date.cpp date.h
		g++ -c date.cpp -o date.o