9-9.exe:9-9.o calculator.o
		g++ 9-9.o calculator.o -o 9-9.exe
9-9.o:9-9.cpp calculator.h stack.h
		g++ -c 9-9.cpp -o 9-9.o
calculator.o:calculator.cpp calculator.h stack.h
		g++ -c calculator.cpp -o calculator.o