7-9.exe:Matrix.o LinearEqu.o 7-9.o
		g++ Matrix.o LinearEqu.o 7-9.o -o 7-9.exe
LinearEqu.o:LinearEqu.cpp Matrix.h LinearEqu.h
		g++ -c LinearEqu.cpp -o LinearEqu.o
Matrix.0:Matrix.cpp Matrix.h
		g++ -c Matrix.cpp -o Matrix.o
